### ISSUE TITLE
Monitorias visiveis por um aluno (discução)

### ISSUE THREAD

**Issue by HaissamHammoud** [Rafa-KozAnd/Projeto_Monitoria_App#13]
Prezados, estava observando um problema estrutural na nossa base de dados, nas buscas que o aluno realiza no app precisamos 

1.  Associas os alunos as disciplinas que o aluno esta cursando,para um aluno de Ciência da computação não ver uma monitoria do curso de biologia. 
2. Ou ter uma entidade Curso associada a disciplina , teria que ser uma relação many to many, pois ao mesmo tempo que uma disciplina tem varios cursos, um curso tem varias disciplinas e o aluno poderia ser vinculado ao curso e as buscas pegam todas as materias do curso que tem monitoria. São duas abordagens diferêntes para o mesmo problema, o que acham senhores? Dai o aluno seria associado a disciplina 

É possivel misturar as duas ideias também, para isso teriamos que ter um CRUD de desciplinas onde coordenador adiciona disciplinas(ou alimenta atravez de um csv) os alunos de um determinado curso conseguem vizualizar as disciplinas do curso que estão cursando usando um filtro e adicionar ao usuario assim aparecem apenas monitorias relacionadas a materias que estão cursando.

O que acham?

**Comment by Rafa-KozAnd** [comment]
Creio que associar o Aluno com as Disciplinas seria adequado, conversei ontem com o João Paredes exatamente sobre isso, as Disciplinas ficaram meio desconexas do restante dos dados, tanto que subimos uma alteração em nossas branchs com essa inclusão.

**Comment by HaissamHammoud** [comment]
Vou criar uma tarefa para associar aluno a um curso assim como, assim como as disciplinas com cursos.
