### ISSUE TITLE
Rota de perfil pedindo senha?

### ISSUE THREAD

**Issue by Verdant31** [Rafa-KozAnd/Projeto_Monitoria_App#36]
![image](https://user-images.githubusercontent.com/71015476/198912648-d0742ce7-7b07-4971-bc76-9cbf25b61132.png)

Não entendi pra que pedir a senha, eu não mantenho a senha salva em lugar nenhum no front por questões de segurança, não tem como mandar pro back de novo depois do login.
O certo é a rota receber o id do aluno e retornar os dados.

**Comment by HaissamHammoud** [comment]
@Verdant31 foi um teste, vou tirar

**Comment by HaissamHammoud** [comment]
estava testando como faria a parte de autenticação e acabou sobrando esse ai pelo jeito

**Comment by HaissamHammoud** [comment]
@Verdant31  enviei um commit corrigindo, quando puder teste?
