### ISSUE TITLE
Rota para pegar as candidaturas do aluno

### ISSUE THREAD

**Issue by Verdant31** [Rafa-KozAnd/Projeto_Monitoria_App#49]
Path: null
Line: null
Implementar a função que retorna pra quais monitorias o aluno se candidatou.
Devolver um array com as informações de: Nome da disciplina, e status da candidatura

**Comment by joaoparedes1** [comment]
Criei um post /candidaturas pro aluno, coloquei o motivo pq achei que precisaria pros que foram recusados

Exemplo de retorno usando matricula "76303175":
![image](https://user-images.githubusercontent.com/88410604/202549809-1bea1dda-7c78-4e38-a865-841f542746ee.png)
