### ISSUE TITLE
Rota para remover monitor

### ISSUE THREAD

**Issue by Verdant31** [Rafa-KozAnd/Projeto_Monitoria_App#51]
Path: /professor/excluimonitor
Body: id_monitor
Criar uma rota para remover um monitor, vai receber o id do monitor pelo body da requisição com o nome de "id_monitor"

**Comment by joaoparedes1** [comment]
Só com o ID do monitor não é informação suficiente pra conseguir tira ele de uma monitoria, preciso do ID da monitoria no lugar (id_monitoria)
